name: pytest & flake8 control push
on: push
jobs:
  qa:
    name: check tests
    runs-on: ubuntu-20.04
    steps:
      - name: checkout on master
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: install pytest & flake8
        run: |
          pip install pytest
          pip install flake8

      - name: run tests
        run: |
          pytest

      - name: run flake8
        uses: py-actions/flake8@v2
